version: "3.7"

services:
  currency-exchange:
    image: decahthuk/microservices-currency-exchange-service:0.0.1-SNAPSHOT
    mem_reservation: 700m
    ports:
        - "8000:8000"
    networks:
        currency-network:
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: hhtp://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  naming-server:
    image: decahthuk/microservices-naming-server:0.0.1-SNAPSHOT
    mem_reservation: 700m
    ports:
      - "8761:8761"
    networks:
      currency-network:

  currency-conversion:
    image: decahthuk/microservices-currency-converison-service:0.0.1-SNAPSHOT
    mem_reservation: 700m
    ports:
      - "8100:8100"
    networks:
      currency-network:
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: hhtp://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  api-gateway:
    image: decahthuk/microservices-api-gateway:0.0.1-SNAPSHOT
    mem_reservation: 700m
    ports:
      - "8765:8765"
    networks:
      currency-network:
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: hhtp://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_reservation: 300m
    ports:
      - "9411:9411"
    networks:
      currency-network:
    depends_on:
      - rabbitmq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672

  rabbitmq:
    image: rabbitmq:3.8.12-management
    mem_reservation: 300m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      currency-network:

networks:
    currency-network: