<html>
<head>
    <meta charset="utf-8">
    <title>Error</title>
    <style>
        @keyframes extramegasuperanimation {
            0% {
                opacity: 0;
                transform: rotate(-540deg) scale(0);
            }

            100% {
                opacity: 1;
                transform: rotate(0) scale(1);
            }
        }
        table {
            color: black;
            background-color: antiquewhite;
        }
        img {
            animation-name: extramegasuperanimation;
            animation-duration: 2s;
        }
        body {
            background-color: #ffc360;
        }
        body {
            background-color: #ffc360;
        }
    </style>
</head>
<body>
<h3>Return to the <a href="/banking/menu">menu</a></h3>
<h1>Something wrong...</h1>
<h2>Seems like one of my services is down... Try again later</h2>
<p>&nbsp;</p>
<p><img src="https://i.postimg.cc/gJ1Xbx9Y/8-M5-Jp-Ac-Zu-AQ.jpg" alt="Грустный шмэбрик" width="560" height="560" >
</body>
</html>