<html>
<head>
    <meta charset="utf-8">
    <title>Conversion</title>
    <style>
        @keyframes datIsFire {
            0% {
                transform: scale3d(1, 1, 1);
            }

            30% {
                transform: scale3d(1.25, 0.75, 1);
            }

            40% {
                transform: scale3d(0.75, 1.25, 1);
            }

            50% {
                transform: scale3d(1.15, 0.85, 1);
            }

            65% {
                transform: scale3d(0.95, 1.05, 1);
            }

            75% {
                transform: scale3d(1.05, 0.95, 1);
            }

            100% {
                transform: scale3d(1, 1, 1);
            }
        }
        body {
            background-color: #ffc360;
        }
        img {
            animation-name: datIsFire;
            animation-duration: 2s;
            animation-iteration-count: infinite;
        }
    </style>
</head>
<body>
    <h3>Return to the <a href="/banking/menu">menu</a></h3>
    <h1>Successful conversion.</h1>
    <h2>${from} new balance: ${newBalanceFrom}</h2>
    <h2>${to} new balance: ${newBalanceTo}</h2>
    <p>&nbsp;</p>
    <p><img src="https://i.postimg.cc/kXFS2r2q/qju-Z1tdj-Gyg.jpg" alt="Крутой" width="560" height="560"></p>
    <a>Raising our country's economy</a>
</body>
</html>