<html>
<head>
    <meta charset="utf-8">
    <title>Main</title>
    <style>
        @keyframes yoooThisAnimIsSomethingFire {
            0% {
                opacity: 0;
                transform: translateX(-250px) rotate(-200deg);
            }

            100% {
                opacity: 1;
                transform: translateX(0) rotate(0deg);
            }
        }
        body {
            background-color: #ffc360;
        }
        img {
            animation-name: yoooThisAnimIsSomethingFire;
            animation-duration: 2s;
        }
    </style>
</head>
<body>
<h1>Alexey's something idk<img src="https://html-online.com/editor/tiny4_9_11/plugins/emoticons/img/smiley-cool.gif" alt="cool" /></h1>
<h3>You are logged in as ${username}</h3>
<h3>Menu:</h3>
<ol>
    <li><a href="/banking/wallet">Wallet</a></li>
    <li><a href="/banking/get-starter-bonus">Get entry bonus</a></li>
    <li><a href="/banking/get-daily-bonus">Get daily bonus</a></li>
    <li><a href="/banking/transactions">Transactions history</a></li>
    <li><a href="/banking/get-course">Valutes course</a></li>
    <li>Convert valutes(I don't want to use js, type path manually, ok?(<span style="color: #6a8759;">/banking/convert/{from}/{to}/{quantity}</span>))</li>
    <li>Transfer some benjamins(I don't want to use js, type path manually, ok?(<span style="color: #6a8759;">/banking/transfer/{to}/{code}/{quantity}</span>))</li>
</ol>
<p>&nbsp;</p>
<p>Всем кузю лакомкина с растишкой, кто сюда зашел!</p>
<p id="image"><img src="https://i.postimg.cc/j2YVC0Vy/V9iy-0-n-YGo.jpg" alt="Бразильский чипсоед" width="560" height="560"/></p>
</body>
</html>